import { Inter } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  listShots,
}: {
  children: React.ReactNode;
  listShots: React.ReactNode;
}) {
  console.log(listShots)
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          {/* {listShots} */}
        </AuthProvider>
      </body>
    </html>
  );
}
